Update action

diff --git a/.github/workflows/generate.yaml b/.github/workflows/generate.yaml
--- a/.github/workflows/generate.yaml
+++ b/.github/workflows/generate.yaml
@@ -13,3 +13,11 @@ jobs:
           curl --request POST \
           --url 'https://kikudle-moe-cf12.vercel.app/api/generate' \
           --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'
+
+          if [ $? -eq 0 ]; then
+            echo 'SUCCESS'
+          else
+            echo 'FAILURE'
+          fi
+
+          
